# Configuration
title: Quy-Huan Nguyen-Phuoc

remote_theme: sighingnow/jekyll-gitbook

toc:
    enabled: true
    h_min: 1
    h_max: 3

collections:
  pages:
    output: true
    sort_by: date
    permalink: /:collection/:year-:month-:day-:title:output_ext
  others:
    output: true
    sort_by: date
    permalink: /:collection/:year-:month-:day-:title:output_ext
# logo:
#description: Final Year Aerospace Engineering Student
#theme: jekyll-theme-minimal
